# Expose the deployment using a Service
apiVersion: v1
kind: Service
metadata:
  name: modulefederation-maritimos-microfront-service-qa
spec:
  selector:
    app: modulefederation-maritimos-microfront-qa
  ports:
    - protocol: TCP
      port: 4231
      targetPort: 80
  type: NodePort
