# Expose the deployment using a Service
apiVersion: v1
kind: Service
metadata:
  name: modulefederation-usuarios-microfront-service-qa
spec:
  selector:
    app: modulefederation-usuarios-microfront-qa
  ports:
    - protocol: TCP
      port: 4230
      targetPort: 80
  type: NodePort


