apiVersion: apps/v1
kind: Deployment
metadata:
  name: modulefederation-se-microfront-deployment-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modulefederation-se-microfront-qa
  template:
    metadata:
      labels:
        app: modulefederation-se-microfront-qa
    spec:
      containers:
      - name: front-vucem30-container-qa
        image: ghcr.io/vucem30/dockerized-modulefederation-se-microfront:1.2.69
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: qa
      imagePullSecrets:
      - name: vucem30registrykey
